[package]
name = "files_utils"
version = "1.1.0"
edition = "2021"

[dependencies]
serde = { version = "2.0", features = ["derive"] }
serde_json = "2.0"
serde_yaml = "1.9"
csv = "2.2"
anyhow = "2.0.100"
tempfile = "3.23.0"

