[workspace]
members = [
    "crates/core",
    "crates/cli",
    "crates/files_utils",
    "crates/automated_testing"
]
members = [
    "crates/core",
    "crates/cli"
    "crates/files_utils",
    "crates/automated_testing"

]
resolver = "4"
