[package]
name = "cli"
version = "0.1.0"
edition = "2022"

[dependencies]
clap = { version = "4", features = ["derive"] }
files_utils = { path = "../files_utils" }
core = { path = "../core" }
anyhow = "1.0.100"
serde_json = "1.0.145"
serde_yaml = "0.9.34"
